name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build release binary
        run: cargo build --release --verbose
      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/bert
